# Discussion

## Main Findings

This project aimed to explore the impact of individual factors on response to EF training given the heterogeneity of previous study results examining efficacy of EF training in ADHD and autistic children. In particular, the current study explored whether participants’ baseline demographic, EF and clinical characteristics, as well as their engagement during EF training (as indexed by time spent training) were predictors and moderators of response to EF training. Age, gender, response inhibition, working memory, EF impairment, ADHD symptoms, autism traits, stimulant medication use, and time on task were used as predictors and moderators of response. The overall goal of the study was to explore how these individual factors were associated with response to Mega Team immediately after training (5 weeks) and at 6 month follow-up on measures of near transfer of training (response inhibition and working memory) and far transfer of training (EF impairment, ADHD symptoms, planning, and fluency) in a sample of 186 ADHD and 67 autistic children. Existing work on computerized EF training interventions have shown that EF training is moderated by age [@cao2020], sex [@flannery2024], ADHD symptom severity [@davis2018], ADHD subtype [@vanderdonk2020], autism traits [@devries2018], baseline working memory [@vanderdonk2020], baseline response inhibition [@dovis2019], and medication use [@holmes2010; @vanderdonk2020]. However, these previous results were often not replicated or were not corrected for multiple comparisons.

Results of the current study revealed several significant predictors and moderators of response to EF training in the ADHD participants but not in the autistic participants. In the ADHD participants, baseline working memory and gender were significant predictors of improvement in response inhibition and baseline EF impairment was a significant predictor of improvement in ADHD symptoms over time regardless of treatment group. In addition, baseline response inhibition and baseline working memory were significantly moderated by treatment group on indices of change in response inhibition and working memory. Finally, time on task was a significant predictor of improvement in working memory across both groups.

### ADHD Group

**Age & Gender**

In the current study, age was not a significant predictor or moderator of EF training related improvement at either time point for any outcome. This is contrary to findings from a review looking across diagnosis groups (typically developing, ADHD, fragile X, and learning disabilities) including participants with an age range of 3-12 years old that showed an age effect whereby younger children benefited more from computerized EF training than older children [@cao2020]. Findings from the @westwood2023 review, however, did not show a similar relationship in studies of 8-14 year old ADHD children only. Given the rapid development of EFs in preschool ages [@reilly2022], our sample of school aged children may not have a wide enough age range to observe age-related influences in EF training related outcomes that may exist earlier in development.

A review of the literature describes minimal group level differences in EF performance by gender across ages, but identifies some differences in development of EFs in children by gender, for example typically developing girls outperforming boys in an attention task at 8-10 years old whereas no gender differences are observed in adolescence [@grissom2019]. In the current analysis, gender predicted improvement in response inhibition at 6 month follow-up irrespective of treatment group such that girls improved more than boys. The results are in line with a recent analysis showing female participants improved more than male participants in attention scores following attention training [@flannery2024], which did not distinguish the presence of a treatment specific effect over and above an effect of time. Altogether, the current results suggest that there are differences in development of EFs in childhood by gender, but no reported differences in response to training.

**EF Characteristics**

Results from the current study support previous findings showing a relationship between baseline response inhibition and improvement in response inhibition (near transfer) as a function of EF training [@dovis2019]. Specifically, we found that that receiving EF training resulted in significantly greater improvement for participants with relatively worse baseline response inhibition than ones who did not receive EF training. This aligns with the theory that weaker baseline EF leaves a greater capacity for improvement as described by @diamond2011 otherwise known as a compensation effect. This pattern has been observed in studies of working memory training [@vanderdonk2020] and attention training [@davis2018], specifically when the EF being measured at baseline (e.g. low working memory) matched the type of EF training (e.g. working memory). However, this same pattern was not observed when using a composite of multiple EF skills as a predictor and moderator [@minder2019], suggesting that a broad metric of multiple EF skills may not be sensitive enough to pick up this relationship. Results from the current study are consistent with previous research showing that worse baseline ability on a specific skill predicted greater improvement on that same skill when the training content matched that deficit pre treatment.

On the other hand, we observed an interaction by treatment group effect such that higher (better) baseline 1-back working memory performance was associated with greater improvement in 2-back working memory in the Mega Team treatment group but not in the TAU control group at 6 month follow up which is contrary to the findings of @vanderdonk2020. This finding is notable given that results from the Mega Team RCT did not show significant group-level (i.e., Mega Team vs TAU) differences in 2-back working memory within the same time frame [@cheungRCT], indicating the presence of a unique treatment response in a subset of the group. A potential explanation for this discrepancy may be the differences in the type of training between the studies. Whereas @vanderdonk2020 administered only working memory training (CogMed) for a longer total session length in their computerized EF training condition, Mega Team training was composed of both response inhibition and working memory training and for a shorter total session length. This resulted in an average of 1125 minutes of total working memory training per participant in the @vanderdonk2020 study and an average of 187.5 minutes of total working memory training per participant in our study over a 5 week training period in both. In general, working memory training doses vary within the literature [see review @robledo-castro2023] with some evidence that higher doses of working memory training could be more effective than lower doses [@alloway2013; @liu2024]. Our results may indicate that in the context of a lower dose of training, individuals with relatively stronger baseline working memory may improve more with training and perhaps that a higher dose of working memory training than what was completed in our study may be required to benefit participants with lower working memory at pre-treatment. This dose-related pattern of improvement has been shown in a sample of typically developing older adults [@matysiak2019].

Our results also show significant cross-EF (i.e. working memory to response inhibition) prediction of response to training at both outcome time points, and significant moderation by treatment group at 6 month follow-up. Higher (better) baseline 1-back working memory predicted greater improvement in response inhibition at 5 weeks post-treatment and at 6 month follow-up overall across treatment groups. More specifically at 6 month follow-up the participants in the Mega Team group with stronger baseline working memory no longer had an advantage over weaker baseline working memory participants as seen in the control group. To date, other studies have not observed this cross-EF moderation effect [@dovis2019; @minder2019; @vanderdonk2020]. This finding may be explained by the relationship between working memory and response inhibition. First, stronger working memory may predict subsequent improvement in response inhibition because both skills rely on overlapping brain regions necessary across EFs such as the fronto-parietal and cingulo-opercular networks [@friedman2022] and may be the result of better developed shared brain regions at baseline across participants (both Mega Team and TAU groups) which result in more improvement as a function of time. However, this explanation would be best supported with results showing a stronger baseline in *either* working memory or response inhibition predicts improvement in the other skill, which is not seen in our study. An alternative explanation may be based in theoretical models of EFs which propose the various ways working memory, response inhibition, and other EF skills may be interrelated and rely on one another in ADHD individuals. For example, some models propose underlying skill deficits that may explain impairments associated with ADHD such as response inhibition [@barkley1997] or working memory [@rapport2008]. Our results align with theoretical models proposing working memory as the key underlying deficit explaining other difficulties in ADHD as we found that improvement in response inhibition at 5 weeks post treatment and at 6 month follow-up was associated with better developed working memory at baseline across Mega Team and TAU groups. It may be that response inhibition development over time in ADHD children may be reliant on earlier working memory ability. Then in response to Mega Team training, this relationship is negated at 6 month follow-up, so baseline working memory no longer explained improvements in response inhibition, indicating all levels of baseline working memory could benefit from Mega Team Training.

Parent rating of EF impairment via the BRIEF-2 rating scale at baseline predicted greater improvement in ADHD symptoms over time across both Mega Team and TAU control groups at 5 weeks post-treatment and at 6 month follow-up. Findings from the literature suggest that EF impairment as rated on the BRIEF-2 is correlated with ratings of ADHD severity [@jacobson2020]. Results align with expectations of the developmental relationship between EF impairment and ADHD symptoms across participants (Mega Team and TAU) over time. However, this relationship was not moderated by treatment group (Mega Team or TAU) at any time point and baseline daily EF impairment scores did not predict or moderate any other outcome. @minder2019 showed that lower parent rated daily EF impairment at baseline was associated with greater improvement in EF impairment after 12 weeks of EF training than in a higher parent rated impairment subgroup, however they did not compare these outcomes with those of a control group’s making it difficult to distinguish the presence of a treatment-specific change in EF impairment. There is no other existing literature that we know of exploring EF impairment as a moderator of response to EF training in ADHD children. Despite non-significant relationships with training outcomes, ratings of daily EF related impairments warrant further investigation as a factor in EF training response. Baseline EF impairment may relate to adherence to treatment protocol especially in interventions with high EF demands in engaging with intervention or minimal rewards or external motivators. Future work should consider the relationship of baseline EF functioning to other training-related factors beyond training outcomes.

**Clinical Characteristics**

Clinical characteristics (e.g. ADHD symptoms, autism traits, stimulant medication use) were not significant predictors or moderators of improvement at either time point for any outcome in the current study. Existing literature has demonstrated a significant effect for ADHD severity [@davis2018], subtype [@vanderdonk2020], autism traits [@devries2018], and stimulant medication status [@holmes2010; @vanderdonk2020] on response to EF training, however, these findings are inconsistent (e.g., no effect of ADHD severity or stimulant medication [@jones2018], no effect of autism traits [@kirk2021]). It is possible that measurement or sample differences explain inconsistent results across studies. In the present study, parent rated clinical characteristics were used as predictors and moderators, whereas studies with significant ADHD severity and subtype used outcomes from diagnostic interviews and psychological report reviews. In the existing literature, autism traits were significant only in an autistic sample, not in another condition (i.e. intellectual and developmental disorders) [@kirk2021], which may explain why they were not a significant predictor of treatment response in our ADHD participants.

**Time on Task**

In the present study, greater time on task during EF training predicted greater improvement on working memory at 5 weeks post-treatment. These findings reflect the importance of engagement with training as individuals who played more practiced their EFs more and therefore improved more at 5 weeks post-treatment. This result is notable within the context of the overall efficacy results showing no significant differences in group-level (Mega Team vs TAU) performance [@cheungRCT]. Previous research has shown evidence of greater efficacy of working memory training because of intervention dosage. This has been observed when dosage was randomly assigned [@alloway2013] and when dosage of training varied due to participants’ motivation to train [@jaeggi2014]. Despite the initially straightforward nature of this relationship, the components underlying a metric like time on task are complex. In the present study, all participants were instructed to play the minigames for the same amount of time so the variation in time played is reflective of individual differences like motivation to play or the influence of caregivers’ EFs on facilitating training (e.g., scheduling). Existing literature indicates there are differences in reward processing and motivation in individuals with neurodevelopmental disorders versus typically developing children suggesting overall deficits in reward processing with variation within and between groups [@dichter2012; @kohls2014]. In line with the literature, Mega Team games were designed based on children and youth’s interests (e.g. variety of games) and efforts were made to support motivation to play with weekly tracker and salience of associated rewards. However, motivation to play and interest in the games were not directly analyzed so future work should investigate whether games and rewards used during Mega Team training were perceived as motivating and rewarding. Existing literature also suggests that the relationship between parent and child EF skills fits within a complex multifaceted framework composed of genetic and socialization factors [@bridgett2015]. Based on this, efforts were made to minimize demands on caregiver EFs to engage with intervention and incorporate the games into their existing lifestyles as much as possible (e.g., focusing on portability of training with minimal reliance on WiFi, providing weekly phone reminders and check ins). Caregivers’ EF ability and level of involvement in facilitating the training were not captured in this study and future research exploring their impact on time on task may be beneficial in understanding these relationships. Notably, many of the design elements described above were a result of engagement with youth and parents, supporting the use of patient-oriented research approaches in digital intervention design [described further in @cheungRCT]. Given the significance of time on task in the present study, future research should aim to better understand barriers and facilitators to engaging with videogame-based EF training, which could impact time spent training by children and thereby impact treatment outcomes.

### Autism Group

The small sample size (N = 67) of autistic children in our sample may have influenced the non-significant findings in the autistic group. Additionally, despite randomization to treatment condition, the Mega Team and TAU groups had some significantly different baseline scores (e.g., baseline response inhibition) potentially restricting the range of scores in each group and interfering with the ability to detect relationships. None of the factors explored were significant in influencing training outcomes for the autism group, conflicting with findings reported by @devries2018 showing autism traits were a significant predictor. This may reflect that the predictors and moderators selected were not specific enough to the autism phenotype as @devries2018 found that baseline flexibility was a significant predictor in training outcomes. Individual factors predicting response to treatment in the autistic participants may need to be approached differently to be more specific to the presentation - for example capturing additional EF skills such as including shifting or examining the severity and variation associated with restricted, repetitive, behaviours and interests in addition to social communication.

### Summary

Overall results highlight the importance of baseline EF profiles and time on task in near transfer of EF training. There were significant factors in the context of both significant overall group-level Mega Team versus TAU differences (e.g. response inhibition) and in the context of no overall differences in response (e.g. 1-back working memory at 5 weeks). This avenue of work has the potential to clarify the key ingredients influencing transfer of training. None of the factors explored were significant moderators of far transfer of training (as indexed by parent rated daily EF impairment, ADHD symptoms, planning, and fluency). Different factors were significant at 5 weeks post treatment (response inhibition and time on task) and at 6 month follow-up (response inhibition and working memory). Baseline response inhibition and time on task during training were significant factors associated with response at 5 weeks post-treatment in improvement in response inhibition and working memory, whereas baseline working memory was a significant factor associated with ongoing benefit or maintenance of gains at 6 month follow-up in improvements in working memory and response inhibition. Age, gender, and clinical characteristics were not meaningful moderators of response.

## Strengths & Limitations

A major strength of this project is the patient-oriented approach. Mega Team minigames and study protocols were designed together with families and youth with lived and living experiences. Iterative feedback was incorporated during pilot phases to optimize child interest and enjoyment in games and convenience and practicality for caregivers. Given the significance of time on task as a predictor of improvement on working memory, future studies should prioritize family and youth perspectives in intervention designs to increase engagement. Efforts to increase enjoyment and convenience are likely to increase accessibility by for example, minimizing demands on parent EFs to facilitate training. Another strength of the current study was the multi-EF training design as there are relatively fewer studies exploring multi-EF training compared to single-EF training [@westwood2023]. Existing work on predictors and moderators of response in multi-skill training is very limited. In addition, the inclusion of a 6 month follow-up to observe predictors and moderators of longer-term benefits or maintenance of effects was another positive of the current study. Several significant relationships appeared at 6 month follow-up that were not present immediately at 5-weeks post-treatment. Evidence from a meta-analysis suggests that within the limited trials looking at overall efficacy at follow-up, there were a range of significant improvements maintained and some small effects emerged only at follow-up [@westwood2023]. Inclusion of a follow-up in understanding predictors and moderators of response clarifies factors associated with not only immediate response but also later consolidation and maintenance of gains. Finally, though not significant, the inclusion of autistic participants is an important step in developing a better understanding of the effects of computerized EF training across overlapping diagnostic categories like ADHD and autism.

Results also need to be considered in the context of study limitations. First, when interpreting the parent questionnaire results, it should be noted that parents were aware of their child’s treatment group. This knowledge may have biased results on parent-reported outcomes (daily EF impairment and ADHD symptoms) due to expectation of improvement and masked the presence of moderators of response. Future studies should seek to incorporate an active sham condition (e.g., games with no EF load) so that parents and children are blinded to minimize inflation of results. Second, data collection for the current study spanned the COVID-19 pandemic which impacted this research like many others during this period. Data was collected from 2018 to 2023 with a subset of participants experiencing delayed follow-up assessments due to lockdowns with 14 participants having post-treatment visits more than 8 weeks after baseline and 10 participants having follow-up visits more than 9 months after baseline. Participant retention was prioritized over strict adherence to post-treatment and follow-up visit schedule given the unprecedented circumstances. Future studies may benefit from incorporating a sensitivity analysis to better understand COVID-19 related impacts on results. Finally, the autism participant group was ultimately quite small and reflected a fairly narrow slice of the population. These participants had average IQ and were primarily verbal. Despite a lack of variation in these characteristics, autism is known to be quite heterogeneous in other aspects as well and so the small sample size may not have captured enough of a range of characteristics to identify potential predictors and moderators. Despite randomization, autistic participants in the Mega Team group had significantly stronger response inhibition performance at baseline than the TAU control group. Given these limitations, results may not accurately capture predictors or moderators of response in autistic individuals. As computerized EF training in autism is currently a fairly small area of study, it would be beneficial for future research efforts to incorporate predictors and moderators of response while exploring overall efficacy.

## Implications & Future Directions

Theoretical implications of this work are relevant to EF models of impairment in ADHD and compensation versus magnification effects in EF skills. Different models have been proposed to explain the roles of various EF skills within ADHD related impairment [for example summary table within @kofler2024] and these findings support the idea that working memory may be a core deficit [@rapport2008] explaining some of the other difficulties observed in ADHD. A better understanding of the relationship between the EF deficits observed in neurodevelopmental disorders is key for improving intervention design. The second theoretical implication addresses hypotheses of how individual differences in EF skills change in response to intervention. Literature is mixed with competing hypotheses suggesting either a compensation effect (i.e., lower baseline EF have greater capacity for improvement) [e.g. @diamond2011] or a magnification effect (i.e., higher baseline EFs are able to benefit more from intervention) [e.g., @vonbastian2014]. We saw evidence for both types of effects in different baseline EF skills and so it remains unknown if the variation could be the result of different skills responding differently to intervention, baseline ability interacting with training intensity, or some other difference in the components of intervention. Further work is needed to identify potential patterns in how baseline EF abilities respond to intervention.

Methodological implications of these results support the inclusion of follow-up appointments in assessments of EF training. In the limited work following up after treatment there is some evidence of improvements emerging only at mid to long term follow-up [@westwood2023]. Our results support the presence of baseline characteristics that may be relevant factors in continued development of skills or retention of training gains at follow-up.

A clinical implication of these findings is the lack of explanation for what factors influence far transfer of computerized EF training as there were no significant moderators of far transfer. The unexplained heterogeneity in far transfer results supports the caution around computerized EF training as a clinically meaningful intervention option at this time [@westwood2023]. Heterogeneity in far transfer results in computerized EF training warrants further work with blinded trial designs to understand predictors and moderators of response.

Another clinical implication is that lower baseline EF impairment (better EF) predicted improvement in ADHD symptoms regardless of group. This relationship adds to our understanding of how real-world EF impairment relates to changes in ADHD symptoms over time. In line with the established gap between EF task performance and EF related impairment [@toplak2013], performance-based EF tasks do not predict later ADHD symptoms [@coghill2014] but parent ratings of EF impairment do [@hawkey2018]. Understanding the mechanisms that translate EF skills to application in real-world settings is essential to identifying factors associated with far transfer of training.

In conclusion, the current study showed that near transfer of response to EF training (as indexed by response inhibition and working memory tasks) was associated with baseline EF characteristics and time spent training but not with baseline clinical or demographic characteristics in ADHD children. Personalizing EF training based on baseline EF characteristics and developing interventions that are engaging may enhance treatment results. EF training may be equally beneficial across a range of clinical presentations as none of the clinical characteristics measured in the current study (e.g., ADHD symptoms or autism traits) were associated with near or far transfer of outcomes. Relevant participant characteristics that are associated with far transfer of training remain unknown. In addition, more work is needed to identify potential characteristics associated with computerized EF training responses in autistic children.
