project:
  type: book

execute: 
  echo: false
  warning: false
  message: false

book:
  title: "Working UofT Thesis Reproducible Report Template using Quarto"
  author: Navi Ram
  date: "2025-07-24"
  chapters:
    - index.qmd
    - 02_methods.qmd
    - 03_results.qmd
    - 04_discussion.qmd
    - references.qmd
  appendices:
    - appendix.qmd
    
crossref:
  appendix-title: "Appendix"
  appendix-delim: ":"

bibliography: references.bib
csl: apa.csl
linkcolor: black

abstract: "This template allows users to create reproducible documents in the required UofT thesis formatting using quarto. This quarto book is written using YAML, R, markdown, and latex syntax. This approach supports integration with citation managers (e.g. Zotero) to manage bibliography and in-text citations, creates cross-referencable figures, tables, and document sections, generates tables and figures using R syntax, dynamically inserts acronyms, and allows integration of text and code. Future updates will introduce APA formatted word doc output options as well."

acknowledgements: "This would not be possible without the UofT latex template (ut-thesis) maintained by jessexknight and the acronymsdown package by rchaput"

department: Department Name
gradyear: 2025
degree: Degree

fig-cap-location: top

header-includes:
  - \usepackage{pdfpages}
  - \usepackage{tocloft}

filters:
  - acronyms
acronyms:
  fromfile: acronym.yml
  insert_loa: "beginning"
  loa_title: "List of Acronyms"
  loa_header_classes:
    - unnumbered

#https://cameronpatrick.com/post/2023/07/quarto-thesis-formatting/ if page numbering with roman numerals 
#ends up being important i can create these templates suggested here

#lastname_firstname_middleinitial(s)_graduationyearmonth_degreedesignator_thesis.pdf
#e.g., Smith_Lorie_L_201711_PhD_thesis.pdf

#ram_navi_202508_MA_thesis

format:
  html: default
  docx: 
    toc: true
  pdf:
    documentclass: ut-thesis
    template-partials:
      - title.tex
      - before-body.tex
      - toc.tex
    toc: true
    toc-depth: 3
    toc-title: Table of Contents
    lot: true
    lof: true
    number-sections: true
    keep-tex: true
    include-in-header: 
      text: |
        \usepackage{tocbibind}

