\pagenumbering{arabic}
# Introduction

## Background

Neurodevelopmental disorders are persistent and impairing lifelong conditions resulting from combined genetic and environmental influences [@faraone2021]. Attention-Deficit/Hyperactivity Disorder (ADHD) is a highly heritable [@pettersson2019] neurodevelopmental disorder diagnosed in approximately 8% of children and youth worldwide [@ayano2023] and is characterized by persistent inattention and/or hyperactivity symptoms causing impairment in multiple settings [@americanpsychiatricassociation2022]. Likewise, autism is a highly heritable neurodevelopmental disorder diagnosed in 1% of children worldwide [@zeidan2022] identified by atypical social communication, sensory differences, and stereotyped patterns of interests and behaviours [@americanpsychiatricassociation2022]. Though distinct, these two disorders are highly co–occurring at roughly 40% with overlapping features and impairment [@rong2021]. Both ADHD and autism are associated with a range of challenges including difficulties with academic achievement, peer relationships, and behaviour regulation [@french2024; @posar2019]. Interventions for ADHD include use of stimulant or non-stimulant medications, behavioural parent training, and environmental accommodations [@faraone2021]. Although each of these may result in improvements at the group level, benefits are generally time limited and impairment remains in many individuals [@faraone2021]. For autism, similar interventions are used (e.g. medications, behavioural therapies, and skills training) but there is no standard treatment approach due to the heterogeneity of presentations and variation in treatment goals [@lord2020].

In response to the demand for novel intervention for neurodevelopmental disorders, there has been an interest in executive function (EF) training-based interventions. Many of the real-world challenges associated with ADHD and autism rely on EF skills [@barkley1997; @diamond2013; @yang2022] which are cognitive processes that are essential for managing behaviours to achieve goals and are often impaired in these neurodevelopmental disorders [@townes2023; @sadozai2024]. Response inhibition, working memory, and shifting are three core interrelated but distinct EF skills [@friedman2017] which are impaired in ADHD and autistic individuals [@townes2023]. Computerized EF training interventions aim to train specific EFs (e.g., working memory) using repetition and adaptive increases in difficulty to strengthen the underlying neural networks by leveraging brain plasticity [@cortese2015]. In general, EF training programs are designed to improve the specific EF(s) being trained (e.g., training in response inhibition leading to improvement on response inhibition tasks) - referred to as near transfer of training, and ultimately onto untrained downstream skills (e.g., training in response inhibition leading to decreased ADHD symptoms) - referred to as far transfer of training [@cortese2015]. Far transfer targets range from lab-based measures not directly trained (e.g. planning, academic fluency) to parent ratings of manifestations of real-life behaviour (e.g. daily EF related impairment). Existing evidence suggests that the use of EF training programs has resulted in near transfer of skill development, whereas their use is less consistently associated with far transfer [see reviews by @cortese2015; @westwood2023].

Computerized EF training has been studied for more than two decades. Over this time, interest in computerized EF training has exploded with more than 15 unique EF training programs for children and more than 36 randomized controlled trials (RCTs) evaluating these programs in ADHD participants and four in autistic participants [see reviews by @pasqualotto2021; @robledo-castro2023; @westwood2023]. Despite limited evidence for overall efficacy of existing computerized EF training programs, several EF training games are used commercially. For example, CogMed Working Memory Training is a popular EF training program which specifically targets working memory skills [@klingberg2002]. This program, however, has been criticized for its lack of far transfer beyond the specific skills trained, the high amount of training time required (45 minutes per day), and cost (\$1500 per child) [@roberts2016]. More recently, EndeavorRx is the first Food and Drug Administration approved video game-based EF training program for ADHD but the near-transfer of effects from the original study evaluating this program [@kollins2020] have yet to be replicated.

A recent review by @robledo-castro2023 that looked at the components of EF training programs suggests that features such as dosage of the interventions, degree of adaptiveness of training, types of devices used, and EFs being trained vary widely across existing programs. Adaptive training (decreasing or increasing difficulty based on performance) is commonly used in EF training programs and is suggested to be an essential component of effective EF training [@cortese2015]. Broadly, the most frequently trained EF in these programs is working memory, while other EFs including attention, response inhibition, or multiple EFs at once have also been the focus [@pasqualotto2021; @robledo-castro2023; @westwood2023]. There is some evidence suggesting that multi-EF training may be superior to single-EF training [@alabdulakareem2020; @cortese2015], whereas a more recent review did not see a greater benefit to multi-EF training than single-EF training [@westwood2023]. Optimization of EF training program features is an area of ongoing work to understand the intervention elements associated with treatment effects.

Some research has investigated participant-level variability in evaluations of EF training programs. For example, ADHD and autism are each heterogeneous disorders with broad clinical presentations [@luo2019; @masi2017] which may result in variation in response to treatment that is masked by treating each diagnosis homogeneously. In addition to the clinical heterogeneity of these disorders, there is individual variation in other pre-treatment features such as the EF skills themselves. For example, executive dysfunction is not a diagnostic criterion in either of these disorders but is a common deficit resulting in a range of impairments, even though EF abilities vary widely within ADHD [@lambek2018] and autistic individuals [@hill2004]. This variability may be associated with a differential response to EF training, potentially explaining the range of group-level results in these disorders. Given the large number of trials for computerized EF training programs with mixed outcomes in ADHD and increasing number in autism, there is a need to better understand the impact of individual pre-treatment characteristics on heterogeneity in EF training intervention results.

## Mega Team

Mega Team is a computerized EF training program co-developed with youth partners. Mega Team is designed to adaptively train working memory and response inhibition using engaging minigames which are played on a laptop and tablet. The Mega Team training algorithm adapts to the individual’s performance and increases or decreases in difficulty based on the user’s performance in order to remain challenging. In the RCT evaluation of Mega Team were randomized to either receive Mega Team training or waitlisted in a treatment as usual (TAU) control group [@cheungRCT]. Mega Team training was administered on average for 25 days over five weeks for 15 minutes per day. At three time points (baseline, immediately post five weeks of treatment, and at follow-up six months after beginning training) participants’ EF task performance and academic fluency were assessed and caregivers provided ratings of EF impairment and ADHD or autism traits. Results showed significant overall near transfer of treatment effects with improved EF performance, far transfer of effects with improved ADHD symptoms and caregiver-rated EF impairment, and no treatment effects on planning or academic fluency in the ADHD participants. Most treatment effects were present at five weeks post-treatment and were maintained until six month follow-up, except for working memory which was not significantly improved immediately after treatment but was significantly improved at six month follow-up. There were no overall treatment effects in the autism participant group. The current study seeks to explore the influence of individual and training level factors on the treatment-effects of Mega Team EF training within this initial RCT evaluation of the program.

## Factors Influencing EF Training Outcomes

### Demographic Characteristics

EF skills develop and strengthen through childhood and adolescence with more rapid development at earlier ages [@best2010], suggesting that younger children may respond better to EF-focused interventions compared to older children. A meta-analysis of computerized EF training identified that most studies to date have been on children and effect sizes amongst these studies have not been related to the participants’ age [@westwood2023]. However, another meta-analysis looking across game-based and traditional computerized EF training interventions found that younger children benefited more from computer-based EF training than older children [@cao2020]. The @westwood2023 meta-analysis focused on ADHD participants of all ages whereas the @cao2020 review looked at multiple neurodevelopmental diagnoses together in children, which may have contributed to the inconsistencies in findings across these meta-analytic reviews.

Gender is an understudied participant characteristic in computerized EF training research. Existing work often refers to sex (biological) and gender (social) interchangeably and consists of largely male samples [e.g., @chacko2014; @dovis2015; @medina2021], with roughly double the number of male to female participants as reported by a recent review [@robledo-castro2023]. Diagnostic rates and presentations vary across sexes in ADHD [e.g., @hasson2012] and autism [@zeidan2022]. For example, in ADHD, “sex differences” may be due to differences in referral and diagnostic rates rather than differential presentation of ADHD, potentially reflecting variation in gender expectations rather than biological sex differences [@assari2021]. EF performance, however, does not systematically differ by gender [@grissom2019]. Interestingly, analysis of sex-based differences in response to EndeavorRx attention training showed greater improvement in attention scores in female participants compared to male participants and acknowledged the lack of available gender information [@flannery2024]. Given the lack of existing work examining the contribution of gender in treatment effects, more research is needed in this area.

### Baseline Clinical Characteristics

Some studies sought to identify baseline (pre-treatment) clinical characteristics of participants who benefit from computerized EF training. For example, previous work has shown that stimulant medication use and EF training together resulted in improvement in working memory more than just medication or training alone [@holmes2010]. Additionally, more recent work has found that children on stimulant medication benefited most from training in their visual spatial working memory and this effect was maintained at six-month follow-up [@vanderdonk2020].

With respect to severity of symptoms, one study found that a high ADHD symptom severity subgroup of participants showed a greater response to treatment on attention and working memory compared to lower ADHD symptom severity participants [@davis2018], however another found no effect of ADHD symptom severity [@jones2018]. In another study, predominantly Inattentive type ADHD participants improved more than Combined type on parent and teacher rated EF impairment (in behavioural regulation) at post-treatment and improved more on word reading accuracy at follow-up [@vanderdonk2020]. Similarly, there are mixed results on the impact of autism traits on the outcomes of computerized EF training. For example, @devries2018 found that less severe autism traits predicted better training outcomes in autistic participants whereas @kirk2021 did not find evidence of autism traits predicting attention outcomes in participants with intellectual and developmental disorders. Altogether, research findings in this area are mixed and warrant further exploration of the influence of clinical characteristics on EF training outcomes.

### Baseline EF Abilities

Existing literature in ADHD participants has shown that baseline working memory predicted and moderated near transfer of working memory skills such that below average and average working memory participants improved on attention and visual spatial working memory tasks whereas performance decreased in above average baseline working memory participants [@vanderdonk2020]. A similar pattern was seen in another study with poorer response inhibition predicting greater improvement in response inhibition following treatment [@dovis2019]. These results align with the idea that individuals with weaker EFs at baseline may leave more capacity for improvement when trained compared to those with stronger EF [@diamond2011]. However, these results were not corrected for multiple comparisons [@vanderdonk2020] or did not remain after correction [@dovis2019]. Conversely, @minder2019 found that the group with low parent-rated EF impairment at baseline improved more than the high impairment group after EF training on parent-rated EF impairment, which aligns more with the theory of a magnification effect whereby individuals with stronger skills are able to gain more from training [e.g., @vonbastian2014]. In an autistic sample of children and youth it was found that better baseline EF (flexibility) predicted improvement in a quality of life measure following working memory and shifting training [@devries2015].

### Engagement with Intervention

Possible dosage effects of computerized EF training have also been examined. For example, @liu2024 found increasing benefits of computerized EF training for every five additional minutes of training per day up to an optimal dose at 25 minutes per day for 6 days a week in adults. @alloway2013 showed that a higher dose of working memory training was more beneficial than a lower dose and @jaeggi2014 identified that greater engagement with intervention was related to greater improvement.

## Aim

Computerized EF training programs have shown consistent growth in development and investigation, with several commercial options currently available. The existing research on efficacy of these programs is variable and largely shows a lack of far transfer to untrained skills. Most videogame-based EF training programs in neurodevelopmental disorders have focused on ADHD, with more recent work exploring applications in autism. However, both disorders are characterized by high heterogeneity in clinical and EF characteristics pointing to potential key factors that may be associated with variability in response to EF training. There has been limited investigation on factors associated with heterogeneity in responses to treatment, which is essential to understand what intervention works best for whom. To address gaps in the research on currently available EF training programs, our team co-created Mega Team with youth co-designers with a focus on accessibility, affordability, and multi-skill training. Overall results of the main RCT show near and far transfer in ADHD participants but not in autistic participants [@cheungRCT]. This project will explore a broad range of baseline predictors to better understand patterns in individual factors of response to computerized EF training in a sample of ADHD and/or autism children.

**Research Question:** Do demographic (age and gender), clinical (use of stimulant medication, ADHD symptoms, autism traits), EF (response inhibition, working memory baseline performance, and EF-related impairment), and training (time on task) factors predict magnitude of response to treatment in near and far transfer (near: response inhibition and working memory; far: ADHD symptoms, daily EF impairment, planning, and fluency) outcome measures immediately after Mega Team training and at six month follow-up in ADHD children and autistic children?
